import { type ConfigPlugin, withAppBuildGradle } from 'expo/config-plugins';

/**
 * tech-06 §7.3 — points the `release` build type at the out-of-tree release keystore.
 *
 * This exists because of tech-04 §1.1. `android/` is generated and `npx expo prebuild --clean`
 * deletes it, so a hand-edit to `android/app/build.gradle` survives exactly until the next
 * prebuild — and the thing being edited is the app's signing identity, whose silent change is
 * unrecoverable. A config plugin is the only edit to the native project that is durable.
 *
 * The default it replaces is the actual hazard: the Expo template signs **release with the debug
 * keystore**, and prebuild regenerates that keystore. So out of the box, every clean rebuild
 * produces a release APK with a different signing identity — and Android refuses to update-install
 * across a key change. The only way forward is uninstall, and per tech-04 §6.5 uninstall destroys
 * `player_id`, the bearer token, the SQLite mirror, and the Health Connect grants, with no recovery
 * path to the server-side profile.
 */

/** Present in the generated file, so re-running prebuild without `--clean` cannot double-append. */
const MARKER = '// traverser-release-signing (tech-06 §7.3)';

const SIGNING_BLOCK = `
${MARKER}
// Generated by app/plugins/withReleaseSigning.ts. Editing this file is pointless — the next
// prebuild deletes android/ and re-injects this block. Change the plugin instead.
def traverserKeystore = project.findProperty('TRAVERSER_KEYSTORE_FILE')
def traverserWantsRelease = gradle.startParameter.taskNames.any { it.toLowerCase().contains('release') }

if (traverserWantsRelease && !traverserKeystore) {
    throw new GradleException(
        "Release build requested but TRAVERSER_KEYSTORE_FILE is not set.\\n" +
        "Set the four TRAVERSER_* properties in ~/.gradle/gradle.properties (see README).\\n" +
        "\\n" +
        "Refusing to fall back to the debug keystore on purpose: a debug-signed release cannot be " +
        "update-installed over a properly signed one, and the only way out of that is an uninstall, " +
        "which destroys the local profile irrecoverably (tech-04 6.5).")
}

if (traverserKeystore) {
    android.signingConfigs.create('traverserRelease') {
        storeFile file(traverserKeystore)
        storePassword project.property('TRAVERSER_KEYSTORE_PASSWORD')
        keyAlias project.property('TRAVERSER_KEY_ALIAS')
        // PKCS12 keystores have no separate key password; keytool ignores -keypass and reuses the
        // store password. The property exists because Gradle requires it, and equals the store one.
        keyPassword project.property('TRAVERSER_KEY_PASSWORD')
    }

    android.buildTypes.release.signingConfig = android.signingConfigs.getByName('traverserRelease')
}
`;

const withReleaseSigning: ConfigPlugin = (config) =>
  withAppBuildGradle(config, (gradleConfig) => {
    if (gradleConfig.modResults.language !== 'groovy') {
      throw new Error(
        `withReleaseSigning expects a Groovy build.gradle, found '${gradleConfig.modResults.language}'.`
      );
    }

    if (!gradleConfig.modResults.contents.includes(MARKER)) {
      gradleConfig.modResults.contents += SIGNING_BLOCK;
    }

    return gradleConfig;
  });

export default withReleaseSigning;
