// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Traverser.Api.Data;

#nullable disable

namespace Traverser.Api.Migrations
{
    [DbContext(typeof(TraverserDbContext))]
    [Migration("20260731214341_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Traverser.Api.Data.Entities.ActivityDay", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<DateOnly>("ActivityDate")
                        .HasColumnType("date")
                        .HasColumnName("activity_date");

                    b.Property<bool>("DailyGearRolled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("daily_gear_rolled");

                    b.Property<DateTime?>("DailyItemClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("daily_item_claimed_at");

                    b.Property<int>("EncountersUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("encounters_used");

                    b.Property<bool>("GoalMet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("goal_met");

                    b.Property<DateTime?>("RestTaggedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rest_tagged_at");

                    b.Property<int>("StepGoalSnapshot")
                        .HasColumnType("integer")
                        .HasColumnName("step_goal_snapshot");

                    b.Property<int>("Steps")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("steps");

                    b.Property<string>("StreakCreditMethod")
                        .HasColumnType("text")
                        .HasColumnName("streak_credit_method");

                    b.Property<int>("Tier1Minutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tier1_minutes");

                    b.Property<int>("Tier2Minutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tier2_minutes");

                    b.Property<int>("Tier3Minutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tier3_minutes");

                    b.Property<int>("XpAwarded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("xp_awarded");

                    b.HasKey("PlayerId", "ActivityDate")
                        .HasName("pk_activity_day");

                    b.ToTable("activity_day", null, t =>
                        {
                            t.HasCheckConstraint("ck_activity_day_encounters_used", "encounters_used <= 5");

                            t.HasCheckConstraint("ck_activity_day_streak_credit_method", "streak_credit_method in ('goal_hit', 'rest_day_tag', 'auto_sync_grace')");
                        });
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.Battle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientBattleId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_battle_id");

                    b.Property<string>("EncounterKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encounter_kind");

                    b.Property<DateTime>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("EnemyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("enemy_id");

                    b.Property<int>("EnemyLevel")
                        .HasColumnType("integer")
                        .HasColumnName("enemy_level");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("XpAwarded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("xp_awarded");

                    b.HasKey("Id")
                        .HasName("pk_battle");

                    b.HasIndex("EnemyId")
                        .HasDatabaseName("ix_battle_enemy_id");

                    b.HasIndex("PlayerId", "ClientBattleId")
                        .IsUnique()
                        .HasDatabaseName("ix_battle_player_id_client_battle_id");

                    b.ToTable("battle", null, t =>
                        {
                            t.HasCheckConstraint("ck_battle_encounter_kind", "encounter_kind in ('wild', 'mini_boss', 'zone_boss', 'tutorial', 'explore')");

                            t.HasCheckConstraint("ck_battle_outcome", "outcome in ('win', 'loss', 'flee')");
                        });
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.ContentVersion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("id");

                    b.Property<DateTime>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_content_version");

                    b.ToTable("content_version", null, t =>
                        {
                            t.HasCheckConstraint("ck_content_version_singleton", "id = 1");
                        });
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.DropRate", b =>
                {
                    b.Property<string>("EncounterKind")
                        .HasColumnType("text")
                        .HasColumnName("encounter_kind");

                    b.Property<string>("RewardKind")
                        .HasColumnType("text")
                        .HasColumnName("reward_kind");

                    b.Property<decimal>("Chance")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("chance");

                    b.Property<int>("QtyMax")
                        .HasColumnType("integer")
                        .HasColumnName("qty_max");

                    b.Property<int>("QtyMin")
                        .HasColumnType("integer")
                        .HasColumnName("qty_min");

                    b.Property<string>("Tier")
                        .HasColumnType("text")
                        .HasColumnName("tier");

                    b.HasKey("EncounterKind", "RewardKind")
                        .HasName("pk_drop_rate");

                    b.ToTable("drop_rate", null, t =>
                        {
                            t.HasCheckConstraint("ck_drop_rate_encounter_kind", "encounter_kind in ('wild', 'mini_boss', 'zone_boss_first', 'zone_boss_repeat', 'daily_goal')");

                            t.HasCheckConstraint("ck_drop_rate_reward_kind", "reward_kind in ('item', 'gear', 'trinket')");
                        });
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.Enemy", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("TypeId")
                        .HasColumnType("text")
                        .HasColumnName("type_id");

                    b.Property<string>("ZoneId")
                        .HasColumnType("text")
                        .HasColumnName("zone_id");

                    b.HasKey("Id")
                        .HasName("pk_enemy");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_enemy_type_id");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("ix_enemy_zone_id");

                    b.ToTable("enemy", null, t =>
                        {
                            t.HasCheckConstraint("ck_enemy_role", "role in ('wild', 'mid_boss', 'zone_boss', 'tutorial')");
                        });
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.EnemyDropPool", b =>
                {
                    b.Property<string>("EnemyId")
                        .HasColumnType("text")
                        .HasColumnName("enemy_id");

                    b.Property<string>("EncounterKind")
                        .HasColumnType("text")
                        .HasColumnName("encounter_kind");

                    b.Property<string>("ItemDefId")
                        .HasColumnType("text")
                        .HasColumnName("item_def_id");

                    b.Property<int>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("weight");

                    b.HasKey("EnemyId", "EncounterKind", "ItemDefId")
                        .HasName("pk_enemy_drop_pool");

                    b.HasIndex("ItemDefId")
                        .HasDatabaseName("ix_enemy_drop_pool_item_def_id");

                    b.ToTable("enemy_drop_pool", (string)null);
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.EnemyMove", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AiWeight")
                        .HasColumnType("integer")
                        .HasColumnName("ai_weight");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("EnemyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("enemy_id");

                    b.Property<int>("Power")
                        .HasColumnType("integer")
                        .HasColumnName("power");

                    b.Property<string>("TypeId")
                        .HasColumnType("text")
                        .HasColumnName("type_id");

                    b.HasKey("Id")
                        .HasName("pk_enemy_move");

                    b.HasIndex("EnemyId")
                        .HasDatabaseName("ix_enemy_move_enemy_id");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_enemy_move_type_id");

                    b.ToTable("enemy_move", null, t =>
                        {
                            t.HasCheckConstraint("ck_enemy_move_ai_weight", "ai_weight between 0 and 100");

                            t.HasCheckConstraint("ck_enemy_move_category", "category in ('physical', 'divine')");
                        });
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.EnemyStatScaling", b =>
                {
                    b.Property<string>("EnemyId")
                        .HasColumnType("text")
                        .HasColumnName("enemy_id");

                    b.Property<string>("Stat")
                        .HasColumnType("text")
                        .HasColumnName("stat");

                    b.Property<decimal>("Base")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("base");

                    b.Property<decimal>("Rate")
                        .HasPrecision(6, 3)
                        .HasColumnType("numeric(6,3)")
                        .HasColumnName("rate");

                    b.HasKey("EnemyId", "Stat")
                        .HasName("pk_enemy_stat_scaling");

                    b.ToTable("enemy_stat_scaling", null, t =>
                        {
                            t.HasCheckConstraint("ck_enemy_stat_scaling_stat", "stat in ('vigor', 'might', 'resolve', 'favor', 'aegis', 'stride')");
                        });
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.GameType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("CycleOrdinal")
                        .HasColumnType("integer")
                        .HasColumnName("cycle_ordinal");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.HasKey("Id")
                        .HasName("pk_game_type");

                    b.HasIndex("CycleOrdinal")
                        .IsUnique()
                        .HasDatabaseName("ix_game_type_cycle_ordinal");

                    b.ToTable("game_type", (string)null);
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.GearDef", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Flavor")
                        .HasColumnType("text")
                        .HasColumnName("flavor");

                    b.Property<string>("GrantsMoveId")
                        .HasColumnType("text")
                        .HasColumnName("grants_move_id");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slot");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tier");

                    b.Property<string>("ZoneId")
                        .HasColumnType("text")
                        .HasColumnName("zone_id");

                    b.HasKey("Id")
                        .HasName("pk_gear_def");

                    b.HasIndex("GrantsMoveId")
                        .HasDatabaseName("ix_gear_def_grants_move_id");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("ix_gear_def_zone_id");

                    b.ToTable("gear_def", null, t =>
                        {
                            t.HasCheckConstraint("ck_gear_def_slot", "slot in ('weapon', 'armor', 'accessory', 'trinket')");

                            t.HasCheckConstraint("ck_gear_def_tier", "tier in ('mortal', 'heroic', 'mythic', 'divine')");
                        });
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.GearMove", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Effect")
                        .HasColumnType("text")
                        .HasColumnName("effect");

                    b.Property<int>("Power")
                        .HasColumnType("integer")
                        .HasColumnName("power");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_id");

                    b.Property<int>("Uses")
                        .HasColumnType("integer")
                        .HasColumnName("uses");

                    b.HasKey("Id")
                        .HasName("pk_gear_move");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_gear_move_type_id");

                    b.ToTable("gear_move", null, t =>
                        {
                            t.HasCheckConstraint("ck_gear_move_effect", "effect in ('weaken', 'fortify', 'swift', 'rend')");
                        });
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.GearTierBonus", b =>
                {
                    b.Property<string>("Tier")
                        .HasColumnType("text")
                        .HasColumnName("tier");

                    b.Property<int>("Flat")
                        .HasColumnType("integer")
                        .HasColumnName("flat");

                    b.Property<decimal>("Rate")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("rate");

                    b.Property<decimal>("TrinketSplit")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("trinket_split");

                    b.HasKey("Tier")
                        .HasName("pk_gear_tier_bonus");

                    b.ToTable("gear_tier_bonus", null, t =>
                        {
                            t.HasCheckConstraint("ck_gear_tier_bonus_tier", "tier in ('mortal', 'heroic', 'mythic', 'divine')");
                        });
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.HrSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("EncounterRollsGranted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("encounter_rolls_granted");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("ExternalSessionId")
                        .HasColumnType("text")
                        .HasColumnName("external_session_id");

                    b.Property<DateTime?>("OveractivityWarnedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("overactivity_warned_at");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Tier1Minutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tier1_minutes");

                    b.Property<int>("Tier2Minutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tier2_minutes");

                    b.Property<int>("Tier3Minutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tier3_minutes");

                    b.HasKey("Id")
                        .HasName("pk_hr_session");

                    b.HasIndex("PlayerId", "ExternalSessionId")
                        .IsUnique()
                        .HasDatabaseName("ix_hr_session_player_id_external_session_id");

                    b.ToTable("hr_session", null, t =>
                        {
                            t.HasCheckConstraint("ck_hr_session_encounter_rolls_granted", "encounter_rolls_granted <= 2");
                        });
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.ItemDef", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("BattleOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("battle_only");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Effect")
                        .HasColumnType("text")
                        .HasColumnName("effect");

                    b.Property<string>("Flavor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flavor");

                    b.Property<int?>("HealPct")
                        .HasColumnType("integer")
                        .HasColumnName("heal_pct");

                    b.Property<int>("MaxStack")
                        .HasColumnType("integer")
                        .HasColumnName("max_stack");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rarity");

                    b.Property<string>("TypeId")
                        .HasColumnType("text")
                        .HasColumnName("type_id");

                    b.HasKey("Id")
                        .HasName("pk_item_def");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_item_def_type_id");

                    b.ToTable("item_def", null, t =>
                        {
                            t.HasCheckConstraint("ck_item_def_category", "category in ('heal', 'buff', 'surge', 'breach')");

                            t.HasCheckConstraint("ck_item_def_effect", "effect in ('weaken', 'fortify', 'swift', 'rend')");

                            t.HasCheckConstraint("ck_item_def_rarity", "rarity in ('common', 'uncommon', 'rare')");
                        });
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.LevelMilestone", b =>
                {
                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("RewardKind")
                        .HasColumnType("text")
                        .HasColumnName("reward_kind");

                    b.Property<string>("GearTier")
                        .HasColumnType("text")
                        .HasColumnName("gear_tier");

                    b.Property<string>("ItemDefId")
                        .HasColumnType("text")
                        .HasColumnName("item_def_id");

                    b.HasKey("Level", "RewardKind")
                        .HasName("pk_level_milestone");

                    b.HasIndex("ItemDefId")
                        .HasDatabaseName("ix_level_milestone_item_def_id");

                    b.ToTable("level_milestone", null, t =>
                        {
                            t.HasCheckConstraint("ck_level_milestone_reward_kind", "reward_kind in ('item', 'gear')");
                        });
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.MilestoneGrant", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("MilestoneKind")
                        .HasColumnType("text")
                        .HasColumnName("milestone_kind");

                    b.Property<string>("MilestoneKey")
                        .HasColumnType("text")
                        .HasColumnName("milestone_key");

                    b.Property<DateTime>("GrantedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("OverflowFallback")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("overflow_fallback");

                    b.HasKey("PlayerId", "MilestoneKind", "MilestoneKey")
                        .HasName("pk_milestone_grant");

                    b.ToTable("milestone_grant", null, t =>
                        {
                            t.HasCheckConstraint("ck_milestone_grant_milestone_kind", "milestone_kind in ('level_item', 'level_gear', 'streak_day', 'zone_entry', 'tutorial')");
                        });
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.PendingReward", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("BonusPrimary")
                        .HasColumnType("integer")
                        .HasColumnName("bonus_primary");

                    b.Property<int?>("BonusSecondary")
                        .HasColumnType("integer")
                        .HasColumnName("bonus_secondary");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("GearDefId")
                        .HasColumnType("text")
                        .HasColumnName("gear_def_id");

                    b.Property<string>("ItemDefId")
                        .HasColumnType("text")
                        .HasColumnName("item_def_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<int?>("LevelAtDrop")
                        .HasColumnType("integer")
                        .HasColumnName("level_at_drop");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("Resolution")
                        .HasColumnType("text")
                        .HasColumnName("resolution");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.HasKey("Id")
                        .HasName("pk_pending_reward");

                    b.HasIndex("GearDefId")
                        .HasDatabaseName("ix_pending_reward_gear_def_id");

                    b.HasIndex("ItemDefId")
                        .HasDatabaseName("ix_pending_reward_item_def_id");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_pending_reward_player_id");

                    b.ToTable("pending_reward", null, t =>
                        {
                            t.HasCheckConstraint("ck_pending_reward_kind", "kind in ('item', 'gear')");

                            t.HasCheckConstraint("ck_pending_reward_resolution", "resolution in ('kept', 'discarded')");
                        });
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AllocAegis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("alloc_aegis");

                    b.Property<int>("AllocFavor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("alloc_favor");

                    b.Property<int>("AllocMight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("alloc_might");

                    b.Property<int>("AllocResolve")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("alloc_resolve");

                    b.Property<int>("AllocStride")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("alloc_stride");

                    b.Property<int>("AllocVigor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("alloc_vigor");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DailyStepGoal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(7000)
                        .HasColumnName("daily_step_goal");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("level");

                    b.Property<long>("LifetimeSteps")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("lifetime_steps");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.Property<string>("TraverserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("traverser_name");

                    b.Property<DateTime?>("TutorialCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tutorial_completed_at");

                    b.Property<int>("UnspentStatPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("unspent_stat_points");

                    b.Property<DateTime>("VigorAnchorAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigor_anchor_at");

                    b.Property<int>("VigorCurrent")
                        .HasColumnType("integer")
                        .HasColumnName("vigor_current");

                    b.Property<int>("XpCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("xp_current");

                    b.Property<long>("XpLifetime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("xp_lifetime");

                    b.HasKey("Id")
                        .HasName("pk_player");

                    b.ToTable("player", null, t =>
                        {
                            t.HasCheckConstraint("ck_player_daily_step_goal", "daily_step_goal >= 3000");

                            t.HasCheckConstraint("ck_player_level", "level between 1 and 60");
                        });
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.PlayerBestiary", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("EnemyId")
                        .HasColumnType("text")
                        .HasColumnName("enemy_id");

                    b.Property<int>("DefeatCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("defeat_count");

                    b.Property<int>("EncounterCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("encounter_count");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.HasKey("PlayerId", "EnemyId")
                        .HasName("pk_player_bestiary");

                    b.HasIndex("EnemyId")
                        .HasDatabaseName("ix_player_bestiary_enemy_id");

                    b.ToTable("player_bestiary", (string)null);
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.PlayerEquippedSkill", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("Slot")
                        .HasColumnType("integer")
                        .HasColumnName("slot");

                    b.Property<string>("SkillId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("skill_id");

                    b.HasKey("PlayerId", "Slot")
                        .HasName("pk_player_equipped_skill");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_player_equipped_skill_skill_id");

                    b.HasIndex("PlayerId", "SkillId")
                        .IsUnique()
                        .HasDatabaseName("ix_player_equipped_skill_player_id_skill_id");

                    b.ToTable("player_equipped_skill", null, t =>
                        {
                            t.HasCheckConstraint("ck_player_equipped_skill_slot", "slot between 1 and 4");
                        });
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.PlayerGear", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AcquiredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acquired_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("BonusPrimary")
                        .HasColumnType("integer")
                        .HasColumnName("bonus_primary");

                    b.Property<int?>("BonusSecondary")
                        .HasColumnType("integer")
                        .HasColumnName("bonus_secondary");

                    b.Property<string>("EquippedSlot")
                        .HasColumnType("text")
                        .HasColumnName("equipped_slot");

                    b.Property<string>("GearDefId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gear_def_id");

                    b.Property<int>("LevelAtDrop")
                        .HasColumnType("integer")
                        .HasColumnName("level_at_drop");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_player_gear");

                    b.HasIndex("GearDefId")
                        .HasDatabaseName("ix_player_gear_gear_def_id");

                    b.HasIndex("PlayerId", "EquippedSlot")
                        .IsUnique()
                        .HasDatabaseName("ix_player_gear_player_id_equipped_slot")
                        .HasFilter("equipped_slot is not null");

                    b.ToTable("player_gear", null, t =>
                        {
                            t.HasCheckConstraint("ck_player_gear_equipped_slot", "equipped_slot in ('weapon', 'armor', 'accessory', 'trinket')");
                        });
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.PlayerItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AcquiredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acquired_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ItemDefId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_def_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_player_item");

                    b.HasIndex("ItemDefId")
                        .HasDatabaseName("ix_player_item_item_def_id");

                    b.HasIndex("PlayerId", "ItemDefId")
                        .HasDatabaseName("ix_player_item_player_id_item_def_id");

                    b.ToTable("player_item", null, t =>
                        {
                            t.HasCheckConstraint("ck_player_item_source", "source in ('wild_drop', 'miniboss_drop', 'boss_drop', 'daily_goal', 'level_milestone', 'streak_overflow', 'zone_entry', 'tutorial')");
                        });
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.PlayerSettings", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<TimeOnly?>("DailyReminderTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("daily_reminder_time");

                    b.Property<decimal>("MusicVolume")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasDefaultValue(1.0m)
                        .HasColumnName("music_volume");

                    b.Property<decimal>("SfxVolume")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasDefaultValue(1.0m)
                        .HasColumnName("sfx_volume");

                    b.HasKey("PlayerId")
                        .HasName("pk_player_settings");

                    b.ToTable("player_settings", (string)null);
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.PlayerSkillDef", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("Power")
                        .HasColumnType("integer")
                        .HasColumnName("power");

                    b.Property<string>("TypeId")
                        .HasColumnType("text")
                        .HasColumnName("type_id");

                    b.Property<int>("UnlockLevel")
                        .HasColumnType("integer")
                        .HasColumnName("unlock_level");

                    b.Property<int?>("Uses")
                        .HasColumnType("integer")
                        .HasColumnName("uses");

                    b.HasKey("Id")
                        .HasName("pk_player_skill_def");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_player_skill_def_type_id");

                    b.ToTable("player_skill_def", null, t =>
                        {
                            t.HasCheckConstraint("ck_player_skill_def_category", "category in ('physical', 'divine')");
                        });
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.PlayerZoneProgress", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("ZoneId")
                        .HasColumnType("text")
                        .HasColumnName("zone_id");

                    b.Property<DateTime>("UnlockedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unlocked_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("PlayerId", "ZoneId")
                        .HasName("pk_player_zone_progress");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("ix_player_zone_progress_zone_id");

                    b.ToTable("player_zone_progress", (string)null);
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.StreakMilestone", b =>
                {
                    b.Property<int>("Day")
                        .HasColumnType("integer")
                        .HasColumnName("day");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slot");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tier");

                    b.HasKey("Day")
                        .HasName("pk_streak_milestone");

                    b.ToTable("streak_milestone", null, t =>
                        {
                            t.HasCheckConstraint("ck_streak_milestone_slot", "slot in ('weapon', 'armor', 'accessory')");

                            t.HasCheckConstraint("ck_streak_milestone_tier", "tier in ('mortal', 'heroic', 'mythic')");
                        });
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.StreakState", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("CurrentStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_streak");

                    b.Property<DateOnly?>("LastCreditedDate")
                        .HasColumnType("date")
                        .HasColumnName("last_credited_date");

                    b.Property<int>("LongestStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("longest_streak");

                    b.HasKey("PlayerId")
                        .HasName("pk_streak_state");

                    b.ToTable("streak_state", (string)null);
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.SyncDelta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("ActivityDate")
                        .HasColumnType("date")
                        .HasColumnName("activity_date");

                    b.Property<DateTime>("AppliedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ClientDeltaId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_delta_id");

                    b.Property<int?>("HrTier")
                        .HasColumnType("integer")
                        .HasColumnName("hr_tier");

                    b.Property<int>("MinutesDelta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("minutes_delta");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<int>("StepsDelta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("steps_delta");

                    b.Property<int>("XpDelta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("xp_delta");

                    b.HasKey("Id")
                        .HasName("pk_sync_delta");

                    b.HasIndex("PlayerId", "ActivityDate")
                        .HasDatabaseName("ix_sync_delta_player_id_activity_date");

                    b.HasIndex("PlayerId", "ClientDeltaId")
                        .IsUnique()
                        .HasDatabaseName("ix_sync_delta_player_id_client_delta_id");

                    b.ToTable("sync_delta", null, t =>
                        {
                            t.HasCheckConstraint("ck_sync_delta_hr_tier", "hr_tier between 1 and 3");

                            t.HasCheckConstraint("ck_sync_delta_source", "source in ('steps', 'hr', 'battle', 'manual')");
                        });
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.TypeEffectiveness", b =>
                {
                    b.Property<string>("AttackerTypeId")
                        .HasColumnType("text")
                        .HasColumnName("attacker_type_id");

                    b.Property<string>("DefenderTypeId")
                        .HasColumnType("text")
                        .HasColumnName("defender_type_id");

                    b.Property<decimal>("Multiplier")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("multiplier");

                    b.HasKey("AttackerTypeId", "DefenderTypeId")
                        .HasName("pk_type_effectiveness");

                    b.HasIndex("DefenderTypeId")
                        .HasDatabaseName("ix_type_effectiveness_defender_type_id");

                    b.ToTable("type_effectiveness", (string)null);
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.XpCurve", b =>
                {
                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("Cumulative")
                        .HasColumnType("integer")
                        .HasColumnName("cumulative");

                    b.Property<int?>("XpToNext")
                        .HasColumnType("integer")
                        .HasColumnName("xp_to_next");

                    b.HasKey("Level")
                        .HasName("pk_xp_curve");

                    b.ToTable("xp_curve", null, t =>
                        {
                            t.HasCheckConstraint("ck_xp_curve_level", "level between 1 and 60");
                        });
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.Zone", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsReleased")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_released");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.HasKey("Id")
                        .HasName("pk_zone");

                    b.HasIndex("Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_zone_ordinal");

                    b.ToTable("zone", (string)null);
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.ZoneGate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("EnemyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("enemy_id");

                    b.Property<string>("GateKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gate_kind");

                    b.Property<bool>("IsHardGate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hard_gate");

                    b.Property<int>("LeagueThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("league_threshold");

                    b.Property<string>("UnlocksZoneId")
                        .HasColumnType("text")
                        .HasColumnName("unlocks_zone_id");

                    b.Property<string>("ZoneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zone_id");

                    b.HasKey("Id")
                        .HasName("pk_zone_gate");

                    b.HasIndex("EnemyId")
                        .HasDatabaseName("ix_zone_gate_enemy_id");

                    b.HasIndex("UnlocksZoneId")
                        .HasDatabaseName("ix_zone_gate_unlocks_zone_id");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("ix_zone_gate_zone_id");

                    b.ToTable("zone_gate", null, t =>
                        {
                            t.HasCheckConstraint("ck_zone_gate_gate_kind", "gate_kind in ('mid_boss', 'final_boss')");
                        });
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.ActivityDay", b =>
                {
                    b.HasOne("Traverser.Api.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activity_day_player_player_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.Battle", b =>
                {
                    b.HasOne("Traverser.Api.Data.Entities.Enemy", "Enemy")
                        .WithMany()
                        .HasForeignKey("EnemyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_battle_enemy_enemy_id");

                    b.HasOne("Traverser.Api.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_battle_player_player_id");

                    b.Navigation("Enemy");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.Enemy", b =>
                {
                    b.HasOne("Traverser.Api.Data.Entities.GameType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_enemy_game_type_type_id");

                    b.HasOne("Traverser.Api.Data.Entities.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_enemy_zone_zone_id");

                    b.Navigation("Type");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.EnemyDropPool", b =>
                {
                    b.HasOne("Traverser.Api.Data.Entities.Enemy", "Enemy")
                        .WithMany("DropPool")
                        .HasForeignKey("EnemyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_enemy_drop_pool_enemy_enemy_id");

                    b.HasOne("Traverser.Api.Data.Entities.ItemDef", "ItemDef")
                        .WithMany()
                        .HasForeignKey("ItemDefId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_enemy_drop_pool_item_def_item_def_id");

                    b.Navigation("Enemy");

                    b.Navigation("ItemDef");
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.EnemyMove", b =>
                {
                    b.HasOne("Traverser.Api.Data.Entities.Enemy", "Enemy")
                        .WithMany("Moves")
                        .HasForeignKey("EnemyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_enemy_move_enemy_enemy_id");

                    b.HasOne("Traverser.Api.Data.Entities.GameType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_enemy_move_game_type_type_id");

                    b.Navigation("Enemy");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.EnemyStatScaling", b =>
                {
                    b.HasOne("Traverser.Api.Data.Entities.Enemy", "Enemy")
                        .WithMany("StatScaling")
                        .HasForeignKey("EnemyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_enemy_stat_scaling_enemies_enemy_id");

                    b.Navigation("Enemy");
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.GearDef", b =>
                {
                    b.HasOne("Traverser.Api.Data.Entities.GearMove", "GrantsMove")
                        .WithMany()
                        .HasForeignKey("GrantsMoveId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_gear_def_gear_move_grants_move_id");

                    b.HasOne("Traverser.Api.Data.Entities.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_gear_def_zone_zone_id");

                    b.Navigation("GrantsMove");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.GearMove", b =>
                {
                    b.HasOne("Traverser.Api.Data.Entities.GameType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_gear_move_game_type_type_id");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.HrSession", b =>
                {
                    b.HasOne("Traverser.Api.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hr_session_player_player_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.ItemDef", b =>
                {
                    b.HasOne("Traverser.Api.Data.Entities.GameType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_item_def_game_type_type_id");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.LevelMilestone", b =>
                {
                    b.HasOne("Traverser.Api.Data.Entities.ItemDef", "ItemDef")
                        .WithMany()
                        .HasForeignKey("ItemDefId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_level_milestone_item_def_item_def_id");

                    b.Navigation("ItemDef");
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.MilestoneGrant", b =>
                {
                    b.HasOne("Traverser.Api.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_milestone_grant_player_player_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.PendingReward", b =>
                {
                    b.HasOne("Traverser.Api.Data.Entities.GearDef", "GearDef")
                        .WithMany()
                        .HasForeignKey("GearDefId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_pending_reward_gear_def_gear_def_id");

                    b.HasOne("Traverser.Api.Data.Entities.ItemDef", "ItemDef")
                        .WithMany()
                        .HasForeignKey("ItemDefId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_pending_reward_item_def_item_def_id");

                    b.HasOne("Traverser.Api.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pending_reward_player_player_id");

                    b.Navigation("GearDef");

                    b.Navigation("ItemDef");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.PlayerBestiary", b =>
                {
                    b.HasOne("Traverser.Api.Data.Entities.Enemy", "Enemy")
                        .WithMany()
                        .HasForeignKey("EnemyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_player_bestiary_enemies_enemy_id");

                    b.HasOne("Traverser.Api.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_bestiary_players_player_id");

                    b.Navigation("Enemy");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.PlayerEquippedSkill", b =>
                {
                    b.HasOne("Traverser.Api.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_equipped_skill_player_player_id");

                    b.HasOne("Traverser.Api.Data.Entities.PlayerSkillDef", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_player_equipped_skill_player_skill_def_skill_id");

                    b.Navigation("Player");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.PlayerGear", b =>
                {
                    b.HasOne("Traverser.Api.Data.Entities.GearDef", "GearDef")
                        .WithMany()
                        .HasForeignKey("GearDefId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_player_gear_gear_defs_gear_def_id");

                    b.HasOne("Traverser.Api.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_gear_players_player_id");

                    b.Navigation("GearDef");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.PlayerItem", b =>
                {
                    b.HasOne("Traverser.Api.Data.Entities.ItemDef", "ItemDef")
                        .WithMany()
                        .HasForeignKey("ItemDefId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_player_item_item_def_item_def_id");

                    b.HasOne("Traverser.Api.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_item_player_player_id");

                    b.Navigation("ItemDef");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.PlayerSettings", b =>
                {
                    b.HasOne("Traverser.Api.Data.Entities.Player", "Player")
                        .WithOne()
                        .HasForeignKey("Traverser.Api.Data.Entities.PlayerSettings", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_settings_player_player_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.PlayerSkillDef", b =>
                {
                    b.HasOne("Traverser.Api.Data.Entities.GameType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_player_skill_def_game_type_type_id");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.PlayerZoneProgress", b =>
                {
                    b.HasOne("Traverser.Api.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_zone_progress_players_player_id");

                    b.HasOne("Traverser.Api.Data.Entities.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_player_zone_progress_zones_zone_id");

                    b.Navigation("Player");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.StreakState", b =>
                {
                    b.HasOne("Traverser.Api.Data.Entities.Player", "Player")
                        .WithOne()
                        .HasForeignKey("Traverser.Api.Data.Entities.StreakState", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_streak_state_player_player_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.SyncDelta", b =>
                {
                    b.HasOne("Traverser.Api.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sync_delta_player_player_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.TypeEffectiveness", b =>
                {
                    b.HasOne("Traverser.Api.Data.Entities.GameType", "AttackerType")
                        .WithMany()
                        .HasForeignKey("AttackerTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_type_effectiveness_game_types_attacker_type_id");

                    b.HasOne("Traverser.Api.Data.Entities.GameType", "DefenderType")
                        .WithMany()
                        .HasForeignKey("DefenderTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_type_effectiveness_game_types_defender_type_id");

                    b.Navigation("AttackerType");

                    b.Navigation("DefenderType");
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.ZoneGate", b =>
                {
                    b.HasOne("Traverser.Api.Data.Entities.Enemy", "Enemy")
                        .WithMany()
                        .HasForeignKey("EnemyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_zone_gate_enemy_enemy_id");

                    b.HasOne("Traverser.Api.Data.Entities.Zone", "UnlocksZone")
                        .WithMany()
                        .HasForeignKey("UnlocksZoneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_zone_gate_zone_unlocks_zone_id");

                    b.HasOne("Traverser.Api.Data.Entities.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_zone_gate_zone_zone_id");

                    b.Navigation("Enemy");

                    b.Navigation("UnlocksZone");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Traverser.Api.Data.Entities.Enemy", b =>
                {
                    b.Navigation("DropPool");

                    b.Navigation("Moves");

                    b.Navigation("StatScaling");
                });
#pragma warning restore 612, 618
        }
    }
}
